### ISSUE TITLE
In DDEcal diag+rot flags bad solutions while diag does not

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#100]
A bad SB (I guess due to RFI) is treated differently if calibrated with diag or diag+rot. In the first case very bad solutions are saved in the h5parm, while in the second case most of the solutions are (correctly) flagged. Is there a different flagging criterion if using the two solvers? Note that the problem is on HBA data. An example MS is in cep3:~fdg/flagonlyrot.MS

parset:
msin = flagonlyrot.MS
msin.datacolumn = DATA
msout = .
msout.datacolumn = CORRECTED_DATA
numthreads = 0 # the pipeline should set this number
steps = [sol]

sol.type = ddecal
sol.uvlambdamin = 30
sol.mode = diagonal # rotation+diagonal
sol.maxiter = 500
sol.tolerance = 1e-3
sol.nchan = 1
sol.solint = 1
sol.propagatesolutions = True
sol.usemodelcolumn = True

**Comment by aroffringa** [comment]
When you're saying "flag solutions", you really mean set the weight of solutions to zero in the hdf5, right?  I'm saying this because I think the solutions should be set to NaN. Is that indeed the case ? If so, then this is possibly a repeat of #44 .

The difference comes from the fact that the rotation constraint results a "derived" value (the rotation), which takes into account the input weights&flags into the derived vlaue, whereas a diagonal constraint does not. A diagonal constraint stays "only" in solution space, and keeps a NaN solution as NaN and the structure is such that the solutions weights of those NaNs are not set to zero -- and hence this is somewhat inconsistent between those two solving modes. It might need a slight architecture overhaul to include solution weights, as they are not propagated. Also the way that the "derived" properties from constraints are propagated is a bit ugly, because it was hacked in later.

**Comment by revoltek** [comment]
The SB I gave as an example has >60% of data flagged and I am expecting a large number of solutions flagged (nans), but using a 0.9 as minvis I get 26/210844 set to nan. Using 0.99 I get the same number.

**Comment by revoltek** [comment]
I notice that most of this cases can be solved with #83.

**Comment by revoltek** [comment]
@aroffringa this can also be closed
