### ISSUE TITLE
smooth constraint + flag

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#128]
It looks like that when the smooth constraint is active no all flags are properly propagated into the h5parm (e.g. fully flagged antennas)

**Comment by aroffringa** [comment]
Indeed, the smoother would set those solutions to zero. Now, the smoother sets them to NaNs and that should propagate via the multidirsolver to the h5parm. @revoltek, could you test branch smoothing-flags ( 64de0d99792cb31945a82c11673416206d12ba85 ) ? 

This is a partial fix that I think solves the problem for you, but what should really happen is that the weights themselves also get smoothed. For example, if a channel is completely missing it would of course still (likely) receive a proper value after smoothing. However, currently it's weight would still remain zero.

In the current DDECal/constraints structure, the constraints aren't able to change the channel weights. I suspect this will not cause problems for now, because if you just use the weights for fitting a TEC afterwards, there's not much difference.

**Comment by revoltek** [comment]
It looks like it's working ok to me! Thanks

**Comment by revoltek** [comment]
I did a ddcal test with multiple directions but I still see the data unflagged (and set to 1 for amp and 0 for phases)

**Comment by aroffringa** [comment]
But it did fix it for single direction? Or nothing changed?

**Comment by revoltek** [comment]
I tried it also in 1 direction and I still see the 0s in the soltab.

**Comment by aroffringa** [comment]
Thanks for testing. I think I've found the issue now; I've run a small solve and I now see the values set to NaNs. It's committed to branch smoothing-flags ( e05c86e6ccc0c73b0523fcf78a0ec7df039b915a ), I'll ask TJ to merge.

**Comment by revoltek** [comment]
I confirm it works ok, thanks!
