### ISSUE TITLE
explode step tries to open last MS twice?

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#132]
Some time ago in september @tammojan put in an "explode" step so that we could e.g. phaseshift the same measurement set to multiple directions at the same time. I think it worked when I tried it back then (it's been a while), but trying it again now it crashes for me with

```
 copying info and subtables ...
Finished preparing output MS
 copying info and subtables ...
Finished preparing output MS

std exception detected: Table lbcs_L335672 already exists
```
or 
```
std exception detected: Invalid Table operation: SetupNewTable lbcs_L394672 is already opened (is in the table cache)
```
with `msout.overwrite=True`. It's always the last measurement set in the list of `msout.name`s that's shown in the error message. Is it maybe trying to open it twice? Below is an example of the parset I use:
```
msin.ntimes = 100 

msout.writefullresflag = False
msout.name = ['lbcs_L394815', 'lbcs_L335672']
msout.storagemanager = dysco

steps = [explode]
explode.steps = [shift, msout]
explode.replaceparms = [shift.phasecenter, msout.name]

shift.type = phaseshift
shift.phasecenter = [[113.182166666667, 43.5945830555556], [113.076458333333, 45.0463888888889]]
```

**Comment by rvweeren** [comment]
Running into the same problem as Frits, I also need to get this working as otherwise the I/O is killing me :-)

**Comment by tammojan** [comment]
This is an issue when using the name `msout` for the split step. To work around this, please use a separate step with type `out`, e.g.
```
msout=

mymsout.type=out
mymsout.writefullresflag = False
mymsout.name = ['msout1', 'msout2']
mymsout.storagemanager = dysco

steps = [explode]
explode.steps = [shift, mymsout]
explode.replaceparms = [shift.phasecenter, mymsout.name]

shift.type = phaseshift
shift.phasecenter = [[113.182166666667, 43.5945830555556], [113.076458333333, 45.0463888888889]]
```

With `msout`, another output step is created after `mymsout`, but the `msout` step will do nothing.

This works, but revealed another issue, which I have fixed in #148.

**Comment by tammojan** [comment]
While the workaround works, the actual bug is that an output step too much is created.

Perhaps @aroffringa can help me fix it: in [line 382 of DPRun.cc](https://github.com/lofar-astron/DP3/blob/master/DPPP/DPRun.cc#L382) a check is made if the last step is an output step. If it is not, it is assumed that an output step needs to be created called `msout.`. This is to make it unneccessary to specify msout explicitly in `steps`. Currently, this check is done against the name of the last step. However, it should check whether the last step created (this is stored in the variable `step` of type `DPStep`) is of the subclass `MSUpdater` or `MSout` (or in fact `Split`). I'm a bit out of shape in terms of C++ polymorphism to fix this.

**Comment by tammojan** [comment]
@aroffringa Never mind, I think I know how to do it without dynamic casting or polymorphism...
