### ISSUE TITLE
No valid solutions if station 0 is flagged in tecandphase mode

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/DP3#190]
DPPP does not produce valued solutions if the first station in the ms is fully flagged. This happens in ddecal tecandphase mode (in this case CS001HBA is 100% flagged). So somehow it is not allowed to have a fully flagged station 0 (almost like there is some referencing going with respect to station 0...).  After applying these h5 solutions (NaNs if I am correct) the entire ms gets flagged.

(this is DPPP is a relatively recent DPPP version in the singularity image make by @tikk3r, so ~few weeks old)

**Comment by tikk3r** [comment]
It's commit https://github.com/lofar-astron/DP3/commit/8cda70fd859dec2b39c6fd5b9bf207967f11305c to be specific.

**Comment by tammojan** [comment]
> It's commit [8cda70f](https://github.com/lofar-astron/DP3/commit/8cda70fd859dec2b39c6fd5b9bf207967f11305c) to be specific.

Sorry, I don't understand. Does this commit introduce flagging everything when the first station is flagged?

**Comment by aroffringa** [comment]
It's the version they use.

I think this is a known issue; ant 0 is used as reference antenna in the phase referencing. That's not necessary though...

**Comment by tammojan** [comment]
Is this in DDECal?

**Comment by aroffringa** [comment]
The second sentence would suggest so yes. Need some coffee TJ :) ?

**Comment by tammojan** [comment]
Yes I do. The line where the phase referencing happens is [here](https://github.com/lofar-astron/DP3/blob/master/DDECal/TECConstraint.cc#L57):
```
// TODO chose this more cleverly?
  size_t refAntenna = 0;
```

So yes, we should do this..

**Comment by aroffringa** [comment]
Hehe yes that's the one. But the referencing is in principe not strictly necessary, as the constraint will automatically do this. Without it, the solver could in theory come up with a TEC value that is quite non-zero for the core stations, but I think because of the number of core stations, they tend not to drift off. So the easiest solution might be to just removing the referencing. A more complicated solution would be to pick a non-flagged station :).

**Comment by tammojan** [comment]
Suggestions (that I could implement):

* Make phase referencing optional from parset
* Choose a reference antenna that is not totally flagged.

Regarding the second point: should the reference antenna be the one with the most non-flagged channels? Or the first antenna with more than 50% unflagged data? Or the first antenna with any unflagged data?

**Comment by aroffringa** [comment]
It should at least be reasonably central, although that's only to interpret the solutions most easily. For the algorithm it doesn't matter.
Indeed parset keys to turn referencing off is a good idea, and probably the quickest fix. The reference antenna could indeed be selected e.g. by the first antenna (so it's core) that's 50% unflagged. I think currently you might lose an entire channel (for all stations) if the reference antenna has a flagged channel, isn't it? Ideally that shouldn't happen either. So there's also something to say about selecting the highest unflagged station. But since the reference station is mostly an aesthetic choice, maybe just doing the first point is good enough for now.

**Comment by rvweeren** [comment]
Selecting the highest unflagged central station would be the best. (adding an option to the parset passes the ball to the user, then the user still needs some simple code to figure out which stations are not highly flagged, doable but less user friendly). 

(most calibration software does automatically switch reference station when it is noticed the reference station is fully flagged, AIPS, casa gaincal, etc.)
