### ISSUE TITLE
DPPP_AOFlag MemoryMax on concatenated MSs

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/DP3#38]
It seems that on measurement sets that have been concatenated in frequency, the memory settings of DPPP_AOFlag are computed based on only one of the MSs. My suspicion is that in the following [line](https://github.com/lofar-astron/DP3/blob/master/DPPP_AOFlag/AOFlaggerStep.cc#L142), `infoIn.nchan()` is computed from one of the MSs, not on the total concatenated thing:
```
double timeSize = (sizeof(casacore::Complex) + sizeof(bool)) *
(infoIn.nbaselines() + 3*nthread) * infoIn.nchan() * infoIn.ncorr();
```

As reported by @adrabent.

**Comment by aroffringa** [comment]
I did a bit of analysis:

- MultiMSReader calls `info().setNChan (itsNrChan)` correctly inside `updateInfo()`
- AOFlagger calculates memory inside its `updateInfo()`
- The info is propagated from earlier steps to later steps by `DPStep::setInfo()`
- MultiMSReader is the first step (DPRun.cc:285)

So this seems to me that this is calculated all correctly. The memory usage is just a guess though, so if it takes too much it might just be possible to set the mem to 25% instead of the default, or so.

**Comment by adrabent** [comment]
Nevertheless, it does not work correctly, if concatenating in frequency, it only sees as if there would be only one subband.
Especially, if someone concats 100 SBs or more in frequency the difference of the used memory is enourmous and leads to very long processing times.

**Comment by aroffringa** [comment]
Okay, thanks for the report. I'll have a look!

**Comment by aroffringa** [comment]
I've did further analysis, and the calculation referred to by @tammojan is done correctly, so that's not the problem. For example, with one subband I see it calculates this:

> Using 31.581 GB of mem.
> One timeslot uses 0.214812 MB.
> Maximum window size: 144134

While with two I see this:
> Using 31.581 GB of mem.
> One timeslot uses 0.429624 MB.
> Maximum window size: 72066

@adrabent what exactly do you call enormous use of memory -- does it take much more than what you allocate it? (AOFlagger is supposed to use _all_ of the memory in the machine, so you can't run multiple DP3s when aoflagger without limitting its usage with the corresponding parset keywords...)

**Comment by aroffringa** [comment]
Hmm there hasn't been a mention of "virtual" concatenation yet... I was concatening in MSSS, with msin=[multiple mses.]. How do you make a virtually concatenated set? It might be that the format of such sets is just incorrect, but I'll have a look (if you can tell me how to make one...)

The "using 31 GB" means there's 31 GB in my machine, which shouldn't change when the nr of channels changes.

**Comment by adrabent** [comment]
Virtual concat is done in that way:

`import pyrap.tables as pt`
`pt.msconcat(list_of_input_ms, output_ms)`

**Comment by aroffringa** [comment]
Thanks for that. I've created a virtually concatenated set and notice it is concatenated by introducing spectral windows. I don't think DPPP supports that at all, but @tammojan might be able to tell you if this is correct.

In any case, flagging a virtually concatenated set probably has little advantages over flagging the individual measurement set, because the flagger can't actually look over the full spectral range when it is split into spectral window. So I don't think this is a usecase that's very generic and should be handled by DP3. (it would be nice to report an error though, instead of segfaulting because of memory usage -- but I don't see any handling of the SPWs in the DPInfo object, so I can't really fix this trivially).

Note that the direct aoflagger program can combine swps, if that's what you want you could use that (see the help for `-combine-spws`, or try it in the gui). Alternatively, you could combine the subbands with DP3 itself, by listing the MSes in the parset. That doesn't create multiple spws, but of course takes more space.
