### ISSUE TITLE
Add leakage solver

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#72]
It would be nice to make some tests on solving leakage. What is missing is a solver that can minimize a matrix like (1, a; b, 1).

**Comment by aroffringa** [comment]
I've added a leakage solver, but it's untested. Could you test it? It's in the branch leakage-solver (97d8e142b7dfb980597bda14baab0a2d613c9561). 

You enable it by doing a dde solve, by adding a keyword `ddecal.leakageconstraint = true` to the parset.

**Comment by aroffringa** [comment]
If it says that you probably didn't compile the leakage solver version. You have to do a `git checkout leakage-solver` to go to the leakage-solver version, as it is not in master yet.

(You have to do `git checkout master` if you wish to go back to master later on)

**Comment by aroffringa** [comment]
It shouldn't, all the relevant code is inside the executable binary, not in libraries. You're using the DDECal step? (it's not implemented in Gaincal)

**Comment by revoltek** [comment]
ok, I think I've it. It's running now, thanks :)

**Comment by aroffringa** [comment]
That probably means the solutions were all NaN, but since the constraint sets the diagonal back to 1 every iteration, those values remain 1.

If you solve without the constraint, you get correct full-Jones solutions out? Did you make sure that the diagonal solutions are already approximately '1' because solving for leakage? (So you've previous done some kind of diagonal calibration).

I'm currently setting the diagonal back to 1. However, if the diagonal is in fact far from one, this probably leads to instability.

**Comment by revoltek** [comment]
If I solve without constrain (same DP3) I get sensible results with off-diag values ~20 and diag values between 50 and 300. I can try to apply the diagonal solution before.

**Comment by aroffringa** [comment]
Ah thanks. I suspect the solutions diverged... but maybe you can give me a small test-case so I can see what happens?

So you have not done some kind of bandpass calibration beforehand, as it seems(?) I didn't really count on that, I assumed that you wanted to solve for the off-diagonals *after* having gotten the diagonals to be about corrected. I think your usecase makes it a bit harder to solve for off-diagonals, since they are dependent on the diagonals. Maybe we should discuss what you're really trying to do and where in your processing you do this...

I'm happy to change the algorithm to do as I mentioned in my previous post, but let's make sure we're thinking about the same thing.

**Comment by revoltek** [comment]
I'll be in ASTRON next week, we can discuss a bit the best strategy and what code could better implement it. In the meanwhile I'll try correcting for the BP in advance.

**Comment by revoltek** [comment]
(I confirm that I get flagged solutions also after applying the bandpass. In the non-constrained run the solution range is 0.1-2)

**Comment by aroffringa** [comment]
I think our conclusion was that a leakage solver is not the right way to do this, so I'll close this bug.
