### ISSUE TITLE
in low S/N regime some stations are set to 0 and some other to high values

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#81]
when I solve diag+rot or diag in regions with noisy data **some** stations are set at 0, **some others** at very high values (the effect varies with different weights). Note that in many cases the first ~half of the stations are set to high values and the second half to 0.

See: https://www.dropbox.com/s/5qlfqi5bg9ol5pz/amp_polXX.png?dl=0

**Comment by aroffringa** [comment]
Could you provide a testset for this? I'm not sure I can look at this any time soon.

**Comment by aroffringa** [comment]
(reposting image here to keep it together with the bugreport -- @revoltek you can paste images right into the ticketbox :-) )
![image](https://user-images.githubusercontent.com/11645549/48670423-f1e6a580-eb17-11e8-9bbc-9fd695009984.png)

**Comment by aroffringa** [comment]
@revoltek Can you post the parset that gives trouble as well?

**Comment by revoltek** [comment]
I've tested it with:

msin =
msin.datacolumn = DATA
msout = .
msout.datacolumn = CORRECTED_DATA

steps = [sol]

sol.type = ddecal
sol.uvlambdamin = 300
sol.mode = diagonal
sol.maxiter = 500
sol.tolerance = 1e-3
sol.nchan = 1
sol.solint = 1
sol.propagatesolutions = True
sol.usemodelcolumn = True

**Comment by revoltek** [comment]
NOTE: I don't see the problem with the DIE solver (same parameters)

**Comment by revoltek** [comment]
This is another example with and without propagate solution. Note that the problem is there (bottom left corner) even with the porp-sol=False, it is just much less problematic as it doesn't spread all over the osbervation.

![amp_polxx](https://user-images.githubusercontent.com/4458741/48936318-da8a2c80-ef0a-11e8-9c84-e806bea3c97c.png)
![amp_polxx](https://user-images.githubusercontent.com/4458741/48936325-e0800d80-ef0a-11e8-8680-44a17cf7b38e.png)

**Comment by revoltek** [comment]
I have at least one example where the DIE solver has the problem enhanced by the prop sol. Conclusion: both algorithm have the problem, propagate solutions makes it worse in both cases. Somewhat the magnitude of the effect is different if using DDE or DIE solver.

**Comment by aroffringa** [comment]
I have analyzed it somewhat. It has to do with the following things:
- Certain solution interval have no unflagged visibility for a given antenna. That antenna is then correctly set to have no solution -- all fine so far.
- When in the next solution interval, that antenna does have unflagged visibilities, its initial value for the solver is initialized to '1', as it has no previous solution.
- At that point, because your final solutions are really far (_3 orders of magnitude!_) from the initial solution of '1', there is one antenna which is really far away from its correct solution, while all the other antennas are already at their final position. I'm not completely sure whether this (also) triggers either the solver to diverge, but in any case the solver stops well before convergence. The latter will happen, because the other antennas are already at the right position, and the stopping criterion (sort of) takes the average convergence over all antennas into account. If you look carefully at areas where things go wrong, it is visible that the high solutions slowly move back to their proper solutions. DDECal is more prone to stop early because it stops with a stopping criterion over all the channels, whereas Gaincal continues each individual channel until that channel has converged.

Whether the weird division between antennas that diverge to high and low values is a bug I'm not sure, and I'll investigate that, but it could also just be due to the particular station that initially had the missing values, and its relation (scale, angle etc.) to the other stations. It could just be whether at that point a station solution correlates or anticorrelates with the 'missing' station's solution.

There are some heuristics that we could build into the solver to remedy some of this, but I think the most important thing to do is to have the solver not be four orders of magnitude away from its final position. Such a bad starting position makes the solver work much harder than it has to, because it has to iterate from the initial position towards the final position. If you just divide your data by 10^8 beforehand (if that indeed brings the solutions approx to Jy levels), this problem is probably gone. You don't need to be within a factor of two, but being 10^8 away from it is really unnecessary...

**Comment by revoltek** [comment]
Thanks for this analysis! Indeed most of the plots I showed are from the OLD correlator which used to set visibilities at ~1e-6 Jy. The new correlator is closer to real flux. A good workaround is to then divide all the visibilities of old datasets by 1e6, as you suggested. The first image you posted, however, is from a new dataset (note the bar on the right is ~200, not 1e-4. It would be good to use that as a testing case (I can prepare 1 SB). An idea: what if instead of an initial value of 1 the station that didn't have data or didn't converge before start at the average value of all the stations that did converge before?

**Comment by aroffringa** [comment]
Yes, I think that's a good idea -- I'll implement that.

But regardless, I think the correlator should output Jy-like values.

**Comment by revoltek** [comment]
There's still something unclear, I tried multiplying all visibilities by 1e6 (note now the solution values are close to 1). However, I still have the propagate solution thing. 
![amp_polxx](https://user-images.githubusercontent.com/4458741/48986545-e0545d80-f116-11e8-9b5e-3f70c4bce0f0.png)

I was also thinking: in these cases ALL stations are wrong, either very high or very low, so I don't see how the solver manage to converge...

**Comment by aroffringa** [comment]
@revoltek Hmm thanks, that's weird. I've now implemented to replace missing solutions by the average absolute gain over the stations (because they are(/can be) complex full-Jones solutions, I've decided to replace missing solutions by the average absolute gain instead of the normal average, because the normal average might be a very low number when the phase turns quickly over the stations. This does mean that missing stations are "reset" to have zero phase solution, but I think the phase converges very quickly.

With these changes, the problem that I saw in your single 4 ch subband seems solved. Before fix (zoomed in on a problematic part of the time axis):
![image](https://user-images.githubusercontent.com/11645549/49012820-ea0fac80-f17a-11e8-807e-2c7ff3ca474a.png)
After fix:
![image](https://user-images.githubusercontent.com/11645549/49012826-f09e2400-f17a-11e8-89ae-9336ca5227e4.png)

**Comment by aroffringa** [comment]
@revoltek Could you try that fix on the test-case that still diverged even when you normalized the vis beforehand?

**Comment by revoltek** [comment]
Am I right that this change should have an impact only when propagate solution = True? Because I see some differences between old dp3 and this branch also when it is = False.

**Comment by revoltek** [comment]
@aroffringa with last update of david and your previous fixes I think this is done.

**Comment by aroffringa** [comment]
Great! Thanks!
